[package]
name = "lisp-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gc-arena.workspace = true
gc-arena-derive.workspace = true
nom.workspace = true
thiserror.workspace = true

[dev-dependencies]
anyhow.workspace = true
