blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/suxiaoshao/lisp/discussions
    about: Use GitHub Discussions for open-ended questions if discussions are enabled for this repository.
